In [1]:
a=10/3
print(a)

3.3333333333333335


In [2]:
a*3

10.0

In [3]:

a=10
b=10
print(id(a))
print(id(b))

140728597478104
140728597478104


Complex: complex is a combination of real and imaginary number.

In [4]:
c=3+4j
print(type(c))
print(f"Real number is {c.real} and imaginary number is {c.imag}")

<class 'complex'>
Real number is 3.0 and imaginary number is 4.0


List:
   -> List is collection of different type data
   -> It is mutable in nature
   -> not sutable foe memory optimization
   -> create with the help of[]

In [5]:
info=['Suman','raj','rajvee',4,7,5,88.8,90.5,86.9]
print(info)
print(type(info))
info[3]='ranbir'
info.append('Ranveer')
info

['Suman', 'raj', 'rajvee', 4, 7, 5, 88.8, 90.5, 86.9]
<class 'list'>


['Suman', 'raj', 'rajvee', 'ranbir', 7, 5, 88.8, 90.5, 86.9, 'Ranveer']

In [6]:
name=[i for i in info if type(i)==float]
name

[88.8, 90.5, 86.9]

In [7]:
new_info=[]
new_info.extend(info)
new_info

['Suman', 'raj', 'rajvee', 'ranbir', 7, 5, 88.8, 90.5, 86.9, 'Ranveer']

In [8]:
name=[]
roll_no=[]
percentage=[]
for i in info:
    if type(i)==str:
        name.append(i)
    elif type(i)==int:
        roll_no.append(i)
    else:
        percentage.append(i)
print(name)
print(roll_no)
print(percentage)

['Suman', 'raj', 'rajvee', 'ranbir', 'Ranveer']
[7, 5]
[88.8, 90.5, 86.9]


Tuple:
   -> It is a collecton of different data types
   -> It is immutable in nature
   -> It is sutable for meory optimization
   -> It is created with the help of ()

red=[255,0,0]
green=[0,255,0]
blue=[0,0,255]
pi=[3.14]
amar colony=[32424,-575675]

In [9]:
t=('Suman','Ani',56,75,27)
t

('Suman', 'Ani', 56, 75, 27)

In [10]:
t.count('Suman')

1

In [11]:
t.index(56)

2

Set:
   -> It is collection of different data types
   -> It is mutable in nature
   -> It don't store the duplicate values
   -> It is created with the help of {}

In [12]:
person_hobbies={'Dancing','Boxing','Singing','Dancing'}
person_hobbies

{'Boxing', 'Dancing', 'Singing'}

How many keywords we have in Python?

It's depend on version to version but in version 3.12.4 is 35.

In [13]:
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))


['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


Dictionary:

   -> It is collection of key value pair.
   -> It does not allow duplicate key value but allows us to store multiple values for same key that too with duplicates.
   -> It is mutable in nature.
   -> It is created with the help of {}

In [14]:
students1={
    'Name':'Suman',
    'Percentage':98
}
students1['Percentage']

98

In [15]:
students={
    'Name':name,
    'roll_no':roll_no,
    'percentage':percentage
}
students['Name']

['Suman', 'raj', 'rajvee', 'ranbir', 'Ranveer']

In [16]:
name=['Suman','Raj','Rajvee']
roll_no=[5,8,2]
percentage=[97,79,60]
students={
    'Name':name,
    'roll_no':roll_no,
    'percentage':percentage
}
students

{'Name': ['Suman', 'Raj', 'Rajvee'],
 'roll_no': [5, 8, 2],
 'percentage': [97, 79, 60]}

In [17]:
name=['Suman','Raj','Rajvee']
roll_no=[5,8,2]
percentage=[97,79,60]
students={
    'Name':name,
    'roll_no':roll_no,
    'percentage':percentage
}
min(students['percentage'])

60

In [18]:
name=['Suman','Ani','Manish']
roll_no=[5,8,2]
percentage=[97,79,60]
students={
    'Name':name,
    'roll_no':roll_no,
    'percentage':percentage
}
sc=max(students['percentage'])
n=students['Name'][students['percentage'].index(sc)]
print(f"{n} who score {sc} is topper of the class")
print(n,"who score",sc,"is a topper of the class")

Suman who score 97 is topper of the class
Suman who score 97 is a topper of the class


In [19]:
students['Name'][students['percentage'].index(60)]

'Manish'

In [20]:
number=[i for i in range(11,21)]
number

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [21]:
n=[]
for i in range(11,21):
    n.append(i)
n

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [22]:
number=[i for i in range(11,23)if i%2==0]
number

[12, 14, 16, 18, 20, 22]

In [23]:
number=[i for i in range(34,54)if i%2!=0]
number

[35, 37, 39, 41, 43, 45, 47, 49, 51, 53]

In [24]:
number=[i**2 for i in range(34,54)if i%2!=0]
number

[1225, 1369, 1521, 1681, 1849, 2025, 2209, 2401, 2601, 2809]

In [25]:
number=[i**2 for i in range(1,11) if i%2==0],[i**3 for i in range(1,11) if i%2!=0]
number

([4, 16, 36, 64, 100], [1, 27, 125, 343, 729])

In [26]:
number=[i**2 if i%2==0 else i**3 for i in range(1,11)]
number

[1, 4, 27, 16, 125, 36, 343, 64, 729, 100]

In [27]:
names=['Suman','ani','manish','neha','pinky']
length=([f"{name} contains {len(name)}" for name in names])
length

['Suman contains 5',
 'ani contains 3',
 'manish contains 6',
 'neha contains 4',
 'pinky contains 5']

Numpy:

    -> It is python library that stands for numeric python.
    -> It provide support for multiple dimensional array and matrices along with collection of mathematical function to operate on these array efficiently.

Need:

    -> Array: It introduce the concept of array which are similar to list in python but store and manipulate large amount of data more efficientlt.

    -> Numerical operation: scalar, relational, logarithms and exponentials.

    -> Efficiency: It is faster than python list.

    -> Broadcasting: Allows operations between arrays of different shape and size.

    -> Integration: Scipy, Pandas, Matplotlib.

Numpy vs List:

    -> Numpy is fix where as list is dynamic.
    -> Numpy contain homogenious data where as list contain all type of data.
    -> Numpy perform difficult operation where as list required large coding.

In [28]:
import numpy as np
n=np.array([12,32,54,65])
print(n)
print(type(n))

[12 32 54 65]
<class 'numpy.ndarray'>


In [29]:
n1=np.array([[1,2,3],[5,4,3]]) #creating 2d array (matrix)
print(n1)

[[1 2 3]
 [5 4 3]]


In [30]:
n2=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])#craeting 3d array (tensor)
print(n2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [31]:
import time
a=[i for i in range(10000)]
b=[i for i in range(10000,20000)]
c=[]
s=time.time()
for i in range (len(a)):
    c.append(a[i]+b[i])
print(time.time()-s)

a1=np.arange(10000)
b1=np.arange(10000,20000)
s1=time.time()
c1=a1+b1
print(time.time()-s1)


0.006147146224975586
0.0009958744049072266


In [32]:
n=np.arange(1,11)
print(n)

n=np.arange(11,23,5)
print(n)

n=np.arange(11,21,2)
n1=np.arange(21,31,2)
print(n+n1)

[ 1  2  3  4  5  6  7  8  9 10]
[11 16 21]
[32 36 40 44 48]


In [33]:
#converting 1D array to 2D array
#2D array
n3=np.arange(12,24)
n3=n3.reshape((4,3))
print(n3)


[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [34]:
#converting 1D array to 3D array
#3D array
n4=np.arange(12,24)
n4=n4.reshape((2,2,3))
print(n4)

[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [35]:
print(np.size(n4))
print(np.shape(n4))
print(np.ndim(n4))


12
(2, 2, 3)
3


In [36]:
#Flatten is used to convert 2d, 3d dimensional array to !D array
f=n4.flatten()
print(f)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [37]:
# creating zeroes matrix array
z=np.zeros((4,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
#craeting ones matrix array
o=np.ones((5,2))
print(o)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
# creating identity matrix array
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
#scalar operation
c1=np.arange(12).reshape((3,4))
print(c1)
print(c1+1)

c1=np.arange(12).reshape((3,4))
print(c1)
print(c1*c1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [41]:
#relationship operation
cl1=np.arange(12).reshape((3,4))
print(cl1)
cl1%2==0

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [42]:
d1=np.random.random((3,3))
d1=np.round(d1*100)
d1

array([[52., 51., 40.],
       [32., 63.,  4.],
       [63., 53., 53.]])

In [43]:
# Seed function is used to generate random values but generate same values for all users
# import numpy as np
np.random.seed(42)
d1=np.random.random((3,3))
d1=np.round(d1*100)
d1

array([[37., 95., 73.],
       [60., 16., 16.],
       [ 6., 87., 60.]])

In [44]:
#Round function help to taking After decimal values
n=12.3457869
round(n)

12

In [45]:
#Round function help to taking After decimal values
n=12.3457869
round(n*100)

1235

In [46]:
#For finding "Max" and "Min" value in the given array
print(f"Max value for each column{np.max(d1,axis=0)}")  #axis=0 for column
print(f"Max value for each row {np.max(d1,axis=1)}")    #axis=1 for row
print(f"min value foe each column{np.min(d1,axis=0)}")  #axis=0 for column
print(f"min value foe each row{np.min(d1,axis=1)}")     #axis=1 for row

Max value for each column[60. 95. 73.]
Max value for each row [95. 60. 87.]
min value foe each column[ 6. 16. 16.]
min value foe each row[37. 16.  6.]


In [47]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[10,11],[12,13]])
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[10 11]
 [12 13]]


In [48]:
#combine by column (vertically)
vstack1=np.vstack((arr1,arr2))
print(vstack1)

[[ 1  2]
 [ 3  4]
 [10 11]
 [12 13]]


In [49]:
#combine by row (horizontally)
hstack1=np.hstack((arr1,arr2))
hstack1

array([[ 1,  2, 10, 11],
       [ 3,  4, 12, 13]])

In [50]:
arr=np.arange(9,19)
arr

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [51]:
#by default, it split vertically
split_arr=np.split(arr,2)
split_arr

[array([ 9, 10, 11, 12, 13]), array([14, 15, 16, 17, 18])]

In [52]:
a=np.array([2,4,1,8])
a=np.arange(10,100)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [53]:
#2D array
arr=np.arange(9,19).reshape((5,2))
arr

array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [54]:
#split by column(vertically)
vsplit_arr=np.vsplit(arr,5)
print(vsplit_arr)

[array([[ 9, 10]]), array([[11, 12]]), array([[13, 14]]), array([[15, 16]]), array([[17, 18]])]


In [55]:
#Split by row (horizontally)
hsplit_arr=np.hsplit(arr,2)
print(hsplit_arr)

[array([[ 9],
       [11],
       [13],
       [15],
       [17]]), array([[10],
       [12],
       [14],
       [16],
       [18]])]


In [56]:
#Putting null value
data=np.array([1,2,np.nan,4,np.nan,6])      #nan is a null value.

In [57]:
#checking null values are present or not
nan_mask=np.isnan(data)     #mask is a fnction for checking null values.   
nan_mask    # "isnan" is used to check in particular data


array([False, False,  True, False,  True, False])

In [58]:
#Checking total null values
nan_mask=np.isnan(data)      #filter out nan values
print(f"total nan values are {nan_mask.sum()}")

total nan values are 2


In [59]:
#For checking non null values
filter_data=data[~nan_mask]   #filter out non nan values
filter_data

array([1., 2., 4., 6.])

In [60]:
#Replacing null values to 0
replaced_data=np.nan_to_num(data,nan=0)
replaced_data

array([1., 2., 0., 4., 0., 6.])

In [61]:
#filter out any avg value
filter_data=data[~nan_mask]   #filter out nan values to avg value
av=np.average(filter_data)

In [62]:
#Replacing null values to any average value without specifying particular value
replaced_data=np.nan_to_num(data,nan=av)
replaced_data

array([1.  , 2.  , 3.25, 4.  , 3.25, 6.  ])

In [63]:
(1+2+4+6)/4

3.25

In [64]:
data1=np.array([1,2,np.nan,4,np.nan,6])
data1

array([ 1.,  2., nan,  4., nan,  6.])

In [65]:
#alternative way
process_data=np.nan_to_num(data1,nan=np.nanmean(data1))
process_data

array([1.  , 2.  , 3.25, 4.  , 3.25, 6.  ])

In [66]:
#alternative way of defining avg value where without finding non nan values we can use
mean_without_nan=np.nanmean(data1)
mean_without_nan

np.float64(3.25)